name: flutter_application_1
description: "A fitness application with workout tracking and user profiles"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  provider: ^6.0.5        # For state management
  shared_preferences: ^2.2.0  # For local storage
  flutter_svg: ^2.0.7     # For SVG support (optional)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/emily.png
    - assets/images/sule.png
    - assets/images/alexsandra.png
    - assets/images/emely.jpg
    - assets/images/image2.png
    - assets/images/image3.png

 